#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAP_DEFAULT_WIDTH  50
#define MAP_DEFAULT_HEIGHT 50

#define NO_ID -1

#define PLAYER_OWNER_ID 0

#define MAX_TECH_PREREQS 4
#define MAX_TECH_UNLOCKS 4
#define MAX_RESEARCH_QUEUE 8

#define ROCKET_TOTAL_STAGES 5

#define ABILITY_COUNT 4

#define RELIGION_VICTORY_THRESHOLD 75

#define DEFAULT_MAX_TURNS  200
#define DEFAULT_NUM_AI     3
#define MAX_AI_FACTIONS    7

#define DIFF_PEACEFUL 0
#define DIFF_EASY     1
#define DIFF_MEDIUM   2
#define DIFF_HARD     3
#define DIFF_EXTREME  4

#define ARRAY_INITIAL_CAPACITY 8

#endif
